feat: add fallback for missing `count` 0 key
gravity-ui/i18n pull request #18
Opened 2022-03-22 08:50 UTC by ogonkov

2022-03-22 09:20 UTC, ValeraS requested changes

2022-03-22 09:20 UTC, ValeraS commented on src/index.ts
> +            }
Как-то странно возвращать массив когда по типам должна быть строка 
```suggestion
            if (Array.isArray(result)) {
                this.warn('Using plural key without params', keysetName, key);
                return key;
            }
            
            result = keyValue;
```

2022-03-22 09:20 UTC, ValeraS commented on src/index.ts
> +            }
Может лучше переделать как-то так?:
```ts
if (Array.isArray(keyValue)) {
  const count = Number(params?.count);
  if (isNaN(count)) {
      this.warn('Missing params.count for key.', keysetName, key);
      return key;
  }
   
   ...
} else {
   result = keyValue;
}

if (params) {
    Object.keys(params).forEach((param) => {
      ...
    });
}
```

2022-03-22 10:39 UTC, ogonkov commented on src/index.ts
> +            }
Распрямил немного условия

2022-03-22 11:06 UTC, ValeraS commented on src/index.ts
> +            result = pluralize(keyValue, count);
Давай добавим проверку, что `keyValue.length` не меньше 3, и возвращать `key` иначе

2022-03-22 11:06 UTC, ValeraS commented on src/index.ts
> +        result = replaceParams(result, params);
Давай возвращать `result` в одном месте
```suggestion
        if (params) {
            result = replaceParams(result, params);
        }
```

2022-03-22 11:26 UTC, ogonkov commented on src/index.ts
> +            result = pluralize(keyValue, count);
ок

2022-03-22 12:10 UTC, ValeraS submitted a review, later dismissed

2022-03-22 12:52 UTC, ValeraS approved these changes

2022-03-23 13:05 UTC, dihar approved these changes

2022-03-23 13:05 UTC, dihar commented on src/types.ts
> +export enum Plural {
Я бы тут явно фиксировал цифровые индексы

2022-03-23 13:06 UTC, dihar commented on src/index.ts
> +            result = pluralize(keyValue, count);
а я бы поставил не меньше 2-х

2022-03-23 13:13 UTC, ogonkov commented on src/types.ts
> +export enum Plural {
зачем? если поломают, то тесты свалятся, при разработке они корректно подсвечиваются по Cmd + наведение

2022-03-23 16:01 UTC, merged